### ISSUE TITLE
Expose the corruption of public servants/law enforcement 

### ISSUE THREAD

**Issue by christyleos** [TechForJustice/project-ideas#12]
Help expose the corruption of public servants/law enforcement. 

Perhaps a way to help share media outside of main stream channels that have been reported as blocking out such media in situations such as the ND pipeline protests. Perhaps some way to circumvent such a blockade. 

Another idea would be a way to share live feeds of these events, unedited and uncensored so that people can see the situation for themselves without questioning if it is edited or fake... real situations in real time.

**Comment by elimisteve** [comment]
@christyleos Interesting! Just mentioned this to a friend. Know of any public data sets that contain information relevant to law enforcement analysis?

**Comment by christyleos** [comment]
I found these and will continue to look for more as we get closer to the hackathon. T4J doesn't have access to any particular data set, and welcome suggestions from people contributing to projects. You can update the list of data sets here > https://github.com/TechForJustice/Datasets-API-Tech-Resources/blob/master/Datasets.md 

https://publicsafetydataportal.org/developers/
http://www.bjs.gov/rawdata.cfm
https://catalog.data.gov/dataset?tags=police
https://data.cityofchicago.org/
http://www.nij.gov/publications/pages/datasets.aspx

**Comment by cclifto** [comment]
I would love to be a part of THIS project!

**Comment by IanColdwater** [comment]
Do y'all have a more concrete idea of what you want to build with this one?

**Comment by shay08** [comment]
I have an help that I need help with, it's called IGotEm it's goal is to provide transparency on our streets involving law enforcement and the public servants.
