### ISSUE TITLE
Chat bot lawyer that fills out protective orders

### ISSUE THREAD

**Issue by christyleos** [TechForJustice/project-ideas#14]
A chat bot that fills out protective orders quickly and efficiently (in Harris County, TX but since this is virtual we can work on it anywhere honestly), so that the user can take the form and present to the courthouse without help from a lawyer. Anyone can come onto the site and have a conversation.

This is my personal project (@christyleos), and fyi I am a tech noob. 

This is where you'll find my [resources, inspiration, and how tos](https://github.com/christyleos/protechme/wiki). 

I am currently using the [Pandorabots Playground](https://playground.pandorabots.com/en/). If anyone is interested in working with me, I'll make it public for ya'll. 

**Roles this project would benefit from:** 
- UX/UI Designer to make sure the  web page is simple
- Domestic violence subject matter expert and/or legal aid SME
- Project Manager to coordinate tasks and create presentation
- Researcher who will find out what the current tech is
- Someone who has worked on a chatbot before, used AIML language

**Comment by chavan** [comment]
I am interested in working on this project

**Comment by christyleos** [comment]
So I'm working on the UX process for the chatbot.

**Comment by christyleos** [comment]
https://github.com/TechForJustice/protechme New Repo, visit to collaborate!

**Comment by christyleos** [comment]
Closing since it has it's own repo
