### ISSUE TITLE
Geo-targeted Voting App

### ISSUE THREAD

**Issue by christyleos** [TechForJustice/project-ideas#15]
An app that is free and provides geo-targeted information on how local officials voted and what propositions are coming up would help empower people to know how their local politicians are voting and whether to vote them out. 

**Roles this project would benefit from:** 
- UX/UI Designer to make sure the platform has a simple and easy interface
- App developer
- Local government subject matter expert or someone who knows the voting arena
- Project Manager to coordinate tasks and create presentation
- Researcher who will find out what the current tech is

**Comment by Rincon805** [comment]
Yes! I'm in. Not sure that no coding knowledge is required though. Seems like someone will have to know how to code the app?
