### ISSUE TITLE
Automated Intake Process for Veterans Treatment Court

### ISSUE THREAD

**Issue by JeffL-T** [TechForJustice/project-ideas#30]
Models:
Denton County, TX veterans court process: [Veterans Court Application Booklet.pdf](https://github.com/TechForJustice/project-ideas/files/709122/Veterans.Court.Application.Booklet.pdf)

GAINS Center for Behavioral Health and Justice Transformation model: https://www.samhsa.gov/gains-center

Housing and the Sequential Intercept Model: https://csgjusticecenter.org/wp-content/uploads/2014/07/Housing-and-the-Sequential-Intercept-Model.pdf

**Comment by christyleos** [comment]
@JeffL-T Can you explain the need for it, and what you are asking the group to specifically build?

**Comment by JeffL-T** [comment]
@christyleos  I have since spoken with Denton County Veterans Services staff and I think I would like to close this one and take it off.  We couldn't clearly identify any opportunities for automation to improve the intake process.  Would you concur with me removing this one?
