### ISSUE TITLE
Veteran Treatment Court tool for meeting program requirements

### ISSUE THREAD

**Issue by christyleos** [TechForJustice/project-ideas#33]
Veteran Treatment Court (VTC) program model includes regular court appearances, treatment sessions, and drug testing with the support of an interdisciplinary team. The program connects veterans to a variety of resources, including employment services, and structured accountability to prevent them from reoffending. Homeless Veterans’ Reintegration Program (HVRP) grantees can play a critical role in meeting the employment needs of these veterans. 

There are 2 use cases that could be developed in conjunction with Veteran Treatment Courts using the Buoy tool (a free and open source technology for connecting users with friends and allies in times of need. ) ;  **one** is for the community surrounding the homeless vets who are being helped by other vets/friends to make sure that they are meeting the requirements of the program that the VTC prescribes - this particular use is consistent with the 'neighborhood' feel for which [Buoy ](https://github.com/betterangels/buoy/wiki)was developed;  **the other** - which would bring Buoy right into the VTC itself, would tie the various members of the staff of the VTC involved with a particular veteran's case, helping the veteran to monitor his/her progress under the program set up as well as to confirm whereabouts. 

Step one: Fork [Buoy ](https://github.com/betterangels/buoy)
Step two: Start building features out

**Comment by JeffL-T** [comment]
VTC experts tell us that a critical component to success of the program is mentor support for the veteran.  In the first instance, Buoy broadens the support network to peers, friends and family; essentially acting as a kind of force multiplier.

**Comment by JeffL-T** [comment]
The BIG IDEA is to develop an online VTC process that also connects a court and treatment team to a particular veteran’s case to monitor progress, and integrates a separate connected network of family, friends and peers who will support the veteran in meeting VTC goals.

**Comment by christyleos** [comment]
The project github can be found here https://github.com/mkhira2/helpOnTheWay

**Comment by christyleos** [comment]
Closing - project has been moved to #42
