### ISSUE TITLE
Supportive Online Tool for Veterans Who've Endured Military Sexual Trauma 

### ISSUE THREAD

**Issue by JeffL-T** [TechForJustice/project-ideas#37]
MST is underreported due to stigma, myths and feelings of helplessness. It is a particular problem with female homeless veterans, with 75 percent being identified as victims of MST.  These women have greater incidents of PTSD than other female combat veterans and are less likely to get help.  The number of female homeless veterans doubled during the first decade of Operation Enduring Freedom.  

There are many efforts among agencies, to promote prevention, response and screening for MST.  The Department of Veterans Affairs (VA) views MST as “an experience” rather than a “diagnosis” and offer free treatment of medical conditions resulting from MST, regardless of service-connection, for those victims who come forward.  Also, virtual reality is being used to treat MST victims.    

The **BIG IDEA** is that an online interactive processes could allow the veteran to anonymously explore reporting options, case reception, validity, targeted resources, obtain counselling, join support groups, build confidence and consider the pros/cons of moving past anonymity to unrestricted reporting.

**Comment by Ryan-Koch** [comment]
I really like this idea. I also don't think there would be a tremendous amount of complexity in developing such a tool, it sounds like with the proper expertise on the processes involved with what you've listed in the big idea paragraph that the data compilation step would be fairly straight forward. The task then would be building out an application to serve that expertise. If there ends up being a team on this for the hack-a-thon, I'd definitely be happy to help.

**Comment by havengoer** [comment]
hello!

I'd like to work on this, and join the team.

Is there a Slack channel for this project?

**Comment by christyleos** [comment]
hi @havengoer ! Join here https://techforjustice-community.herokuapp.com/ and the channel is #militarysexualtrauma

**Comment by christyleos** [comment]
a solution exists so we are discussing pivoting https://www.safehelpline.org/about-mobile

**Comment by christyleos** [comment]
we decided to keep going since the our project will be a significant improvement on the current app

**Comment by christyleos** [comment]
This project now has it's own repo https://github.com/TechForJustice/Carry-On

**Comment by christyleos** [comment]
Closing issue due to move
