### ISSUE TITLE
Web App Connecting Veterans with Mental Health Professionals

### ISSUE THREAD

**Issue by mkhira2** [TechForJustice/project-ideas#38]
Our goal is to offer a web application that offers a log-in for veterans where they can input their income or per-session payment cap. Mental health professionals can log-in and input the price range they're willing to work with.

We can connect the two together and offer a map of mental health professionals displayed to veterans that fit their price criteria.

**Comment by JeffL-T** [comment]
I think one incarnation of this idea might be an app to obtain online counseling for housebound veterans.  F2F MH services can be found for free in some cases (in Dallas anyway), but plenty of veterans are housebound and I believe would pay for an online service.  Also, veterans who incur a travel burden, such as to a VA facility several hours away for MH help, could really benefit from this idea.

**Comment by christyleos** [comment]
@mkhira2  closing since ya'll came up w/  a new idea - please post when you get the chance.
